language: php
php: '7.1'
sudo: false
cache: yarn
branches:
  only:
    - master
env:
  - NODE_JS_VERSION=8.1.3
addons:
  mariadb: '10.0'
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - yarn
cache:
  directories:
    - "$HOME/.nvm"
    - node_modules
    - api/vendor
before_install:
  - mysql -e 'CREATE DATABASE memberhive;'
  - phpenv config-rm xdebug.ini
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then pecl channel-update pecl.php.net; fi;
  - curl -o ~/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
  - bash -c "source ~/.nvm/nvm.sh; nvm install $NODE_JS_VERSION; node --version"
  - nvm use $NODE_JS_VERSION
  - nvm alias default $NODE_JS_VERSION
  - npm i -g @angular/cli typescript@2.4.1 tslint
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm set progress=false
before_script:
  - export NODE_ENV="travis"
  - yarn install:all
script:
  - yarn build:web
  - yarn lint
after_success:
  - ls web/dist/
  - ls core/dist/
