language: php
php: '7.1'
sudo: false
cache: yarn
branches:
  only:
    - master
env:
  - NODE_JS_VERSION=9.5.0
addons:
  mariadb: '10.2'
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - yarn
      - g++-4.8
cache:
  directories:
    - "$HOME/.nvm"
    - node_modules
    - api/vendor

before_install:
  - export CXX=g++
  - export CC=gcc
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX=g++-4.8; fi
  - mysql -e 'CREATE DATABASE memberhive;'
  - phpenv config-rm xdebug.ini
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]] ; then pecl channel-update pecl.php.net; fi;
  - curl -o ~/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.6/nvm.sh
  - bash -c "source ~/.nvm/nvm.sh; nvm install $NODE_JS_VERSION; node --version"
  - nvm use $NODE_JS_VERSION
  - nvm alias default $NODE_JS_VERSION
  - yarn global add @angular/cli@latest @nrwl/schematics
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm set progress=false
before_script:
  - export NODE_ENV="travis"
  - yarn
script:
  - yarn build
  - yarn lint
after_success:
  - ls dist/
