language: node_js
node_js:
  - 6.9
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.nvm"
    - node_modules
    - api/vendor
before_install:
  - npm i -g angular-cli@latest typescript@2.0.10 tslint
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm set progress=false
install:
  - npm install --optional
  - cd api && composer install
before_script:
  - export NODE_ENV="travis"
script:
  - ng build
after_success:
  - ls dist/
